### ISSUE TITLE
R vesion

### ISSUE THREAD

**Issue by jhT1995** [randel/MIND#2] opened 2019-07-01 02:11 UTC
i have tried some version of R, but all of them defeat to install MIND package from github, which version could success to install this package?

**Comment by randel** [comment] 2019-07-01 18:01
What versions have you tried and what is your operating system? I have tried some but it works. Would you mind pasting your `sessionInfo()` results?

If you see an error like `Timeout was reached: Resolving timed out after 10000 milliseconds`, please check your internet connection and try to install it multiple times.

**Comment by jhT1995** [comment] 2019-07-02 01:56
Actually, i have tried R-3.2.2 and R-3.5.0,  I have solved the problem by updata the curl package in R-3.5.0, but i can't connect the github url, and finally i download MIND code from github, and upload to the server,and success install the package.  but now i have another problem, when i use the est_frac(), i using the subset of example$X and deconv$A as the input bulk and sig data respectively, 
the  head of bulk data 
![image](https://user-images.githubusercontent.com/33151001/60476779-70f7ab00-9caf-11e9-91cf-c27900503949.png)

the sig data
![image](https://user-images.githubusercontent.com/33151001/60476793-81a82100-9caf-11e9-9da0-d73fa39f8305.png)
 and i get this error
![image](https://user-images.githubusercontent.com/33151001/60476825-95ec1e00-9caf-11e9-932d-e469ea0fd7e4.png)

**Comment by randel** [comment] 2019-07-02 02:04
I guess the installation issue may be caused by other packages. It works for me every time to test the package on Linux or Windows for different versions of R.

Yes, I just found this bug and fixed it. It is because I changed the dimension in this version. Now it should work. Thanks for catching this!

**Comment by jhT1995** [comment] 2019-07-02 02:19
it is not work for me, it show the same erorr

**Comment by randel** [comment] 2019-07-02 02:27
Have you updated the package? Or you can use `fix(est_frac)` to change one line of code.
https://github.com/randel/MIND/commit/dab469e13647cfcd8d47baaa94779c2e6c4d950e

**Comment by jhT1995** [comment] 2019-07-02 02:36
Could you show me your modified code, I don't konw how to change the code
![code](https://user-images.githubusercontent.com/33151001/60478440-4c9ecd00-9cb5-11e9-8324-b057a579972b.png)

**Comment by randel** [comment] 2019-07-02 02:38
As shown in the link of my last response:
from `  rownames(nls) = rownames(bulk)`
to  `rownames(nls) = colnames(bulk)`.

**Comment by jhT1995** [comment] 2019-07-02 03:39
thanks a lot! this problem have solved.

**Closed** 2019-07-04 19:46 UTC
